name: Jupyter

on: 

  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'
  
jobs:

  build:
    runs-on: ubuntu-latest 
    
  steps:
    - id: repo
      name: Repo Checkout
      uses: actions/checkout@v3
    
    - id: python
      name: Python Setup & Packages Installation
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    
    - id: jupyter
      name: Jupyter Notebook Execution
      run: jupyter execute AI_Lab.ipynb
      shell: bash
      
    - id: commit
        name: Commit Files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add *

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
